### ISSUE TITLE
fatal error: 'SDInternalMacros.h' file not found

### ISSUE THREAD

**Issue by pacu** [SDWebImage/SDWebImage#2774]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | e.g. 12.0 / 10.14.0 / 12.0 / 5.0
 SDWebImage Version     | master
 Integration Method      | SPM
 Xcode Version           | Xcode 11 beta
 Repro rate              |  all the time (100%) 
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

import SDWebImage from master branch using Swift Package Manager
```` 
Library/Developer/Xcode/DerivedData/MovieAppSwiftUI-gdefcjtoyzsyfjbmummmatqajdno/SourcePackages/checkouts/SDWebImage/SDWebImage/SDImageCodersManager.m:13:9: fatal error: 'SDInternalMacros.h' file not found
#import "SDInternalMacros.h"
        ^~~~~~~~~~~~~~~~~~~~
1 error generated.
````

**Comment by dreampiggy** [comment]
@pacu Xcode 11 beta's bug. Xcode does not obey what documentation says about the Package.swift's `cSettings API`

Try

```
swift build
```

This works. Or see more in #2756 

See: 

![image](https://user-images.githubusercontent.com/6919743/60231393-a5442380-98cb-11e9-93cc-8ca3e8af671d.png)

**Comment by pacu** [comment]
thanks @dreampiggy ```swift build``` works, but I can't integrate the package to my project :( I hope Apple fixes this quickly.

**Comment by dreampiggy** [comment]
Still not been fixed in Xcode 11 beta 3.

![image](https://user-images.githubusercontent.com/6919743/60567729-7df2c800-9d9d-11e9-8a85-f6286b67fef5.png)

**Comment by dreampiggy** [comment]
Another suck thing. When I want to use `unsafeFlags` API, Xcode says:


![image](https://user-images.githubusercontent.com/6919743/60570319-e6dd3e80-9da3-11e9-91eb-473b2e460337.png)

So until Apple fix these issues, we can not provide any help. It's recommaned to use Swift CLI instead of Xcode.

**Comment by dreampiggy** [comment]
This issue is fixed by Xcode 11-Beta4. So I just close ?

**Comment by dreampiggy** [comment]
@pacu But SwiftPM current still has issues, compared to CocoaPods/Carthage. I'm working on it. I'll notify you once I submit the PR.

**Comment by dreampiggy** [comment]
@pacu See my fix here #2797 

You can also try this demo repo for SwiftPM integration of SDWebImage.

https://github.com/dreampiggy/SDWebImageSwiftUIDemo

**Comment by pacu** [comment]
awesome! I'm on the go at the moment and I haven't downloaded the latest xcode beta yet. I'll give it a try when I do so as soon as I can

**Comment by sukhrobkhakimov** [comment]
@dreampiggy The problem still exists with XCode 12.3 and Swift 5.3
